CATEGORY_TO_PART = {
    "Overcoat": "outerwear",
    "bag": "accessory",
    "blazers": "outerwear",
    "blouse": "top",
    "coats": "outerwear",
    "croptop": "top",
    "dress": "full_body",
    "hat": "accessory",
    "hoodie": "outerwear",
    "jacket": "outerwear",
    "jeans": "bottom",
    "outwear": "outerwear",
    "shirt": "top",
    "shoes": "accessory",
    "shorts": "bottom",
    "skirt": "bottom",
    "suit": "full_body",
    "sunglasses": "accessory",
    "sweater": "top",
    "trousers": "bottom",
    "tshirt": "top",
}
